# Generated by Django 3.2.6 on 2023-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USR', 'user'), ('ADM', 'admin')], default='USR', help_text='Выберите роль пользователя', max_length=3, verbose_name='Роль пользователя'),
        ),
    ]
